### ISSUE TITLE
ValueError: No header line found in table

### ISSUE THREAD

**Issue by eleonorazari** [jcbird/ppv#13]
Hi Jon,

I am trying to read 2020.09.y.bhm-mwm, but I get the ValueError above. I copied the code below.

Thanks, 
Eleonora

> ppv.fiveplates.available_plateruns()

['2020.08.x.bhm-mwm',
 '2020.10.x.mwm-bhm',
 '2020.10.z.bhm-mwm',
 '2020.10.y.mwm-bhm',
 '2020.08.yy.mwm-bhm',
 '2020.08.y.mwm-bhm',
 '2020.08.xx.mwm-bhm',
 '2020.08.z.mwm-bhm',
 '2020.08.x.mwm-bhm',
 '2020.09.x.bhm-mwm',
 '2020.09.y.bhm-mwm']

> platerun_y = ppv.fiveplates.Platerun('2020.09.y.bhm-mwm')

ValueError                                Traceback (most recent call last)
~/anaconda3/envs/ppv/lib/python3.8/site-packages/astropy/io/ascii/ui.py in _guess(table, read_kwargs, format, fast_reader)
    463             reader = get_reader(**read_kwargs)
--> 464             dat = reader.read(table)
    465             _read_trace.append({'kwargs': copy.deepcopy(read_kwargs),

~/anaconda3/envs/ppv/lib/python3.8/site-packages/astropy/io/ascii/basic.py in read(self, table)
    153         """
--> 154         out = super().read(table)
    155 

~/anaconda3/envs/ppv/lib/python3.8/site-packages/astropy/io/ascii/core.py in read(self, table)
   1173         # Get the table column definitions
-> 1174         self.header.get_cols(self.lines)
   1175 

~/anaconda3/envs/ppv/lib/python3.8/site-packages/astropy/io/ascii/core.py in get_cols(self, lines)
    587             else:  # No header line matching
--> 588                 raise ValueError('No header line found in table')
    589 

ValueError: No header line found in table

During handling of the above exception, another exception occurred:

InconsistentTableError                    Traceback (most recent call last)
<ipython-input-16-ba7fc7303cea> in <module>
----> 1 platerun_10y = ppv.fiveplates.Platerun('2020.09.y.bhm-mwm')

~/anaconda3/envs/ppv/lib/python3.8/site-packages/ppv-0.0.1-py3.8.egg/ppv/fiveplates.py in __init__(self, run_name)
    183             pass  # all is well, platerun available
    184         self.name = run_name
--> 185         self.platesummary = io.load_fiveplates_summary(run_name)
    186         self.fieldnames = self._get_fields()
    187 

~/anaconda3/envs/ppv/lib/python3.8/site-packages/ppv-0.0.1-py3.8.egg/ppv/data/io.py in load_fiveplates_summary(platerun)
     73     else:
     74         raise FileNotFoundError(os.fspath(summary_file))
---> 75     return ascii.read(os.fspath(summary_file), header_start=1,
     76                       format='commented_header')
     77 

~/anaconda3/envs/ppv/lib/python3.8/site-packages/astropy/io/ascii/ui.py in read(table, guess, **kwargs)
    285         # through below to the non-guess way so that any problems result in a
    286         # more useful traceback.
--> 287         dat = _guess(table, new_kwargs, format, fast_reader)
    288         if dat is None:
    289             guess = False

~/anaconda3/envs/ppv/lib/python3.8/site-packages/astropy/io/ascii/ui.py in _guess(table, read_kwargs, format, fast_reader)
    494                    '************************************************************************']
    495             lines.extend(msg)
--> 496             raise core.InconsistentTableError('\n'.join(lines))
    497 
    498 

InconsistentTableError: 
ERROR: Unable to guess table format with the guesses listed below:
Reader:FastCommentedHeader fast_reader: {'enable': True} fill_values: [('', '0')] header_start: 1
Reader:CommentedHeader delimiter: '|' fast_reader: {'enable': True} fill_values: [('', '0')] header_start: 1 quotechar: '"'
Reader:CommentedHeader delimiter: '|' fast_reader: {'enable': True} fill_values: [('', '0')] header_start: 1 quotechar: "'"
Reader:CommentedHeader delimiter: ',' fast_reader: {'enable': True} fill_values: [('', '0')] header_start: 1 quotechar: '"'
Reader:CommentedHeader delimiter: ',' fast_reader: {'enable': True} fill_values: [('', '0')] header_start: 1 quotechar: "'"
Reader:CommentedHeader delimiter: ' ' fast_reader: {'enable': True} fill_values: [('', '0')] header_start: 1 quotechar: '"'
Reader:CommentedHeader delimiter: ' ' fast_reader: {'enable': True} fill_values: [('', '0')] header_start: 1 quotechar: "'"
Reader:CommentedHeader delimiter: '\\s' fast_reader: {'enable': True} fill_values: [('', '0')] header_start: 1 quotechar: '"'
Reader:CommentedHeader delimiter: '\\s' fast_reader: {'enable': True} fill_values: [('', '0')] header_start: 1 quotechar: "'"
Reader:CommentedHeader fast_reader: {'enable': True} fill_values: [('', '0')] header_start: 1

************************************************************************
** ERROR: Unable to guess table format with the guesses listed above. **
**                                                                    **
** To figure out why the table did not read, use guess=False and      **
** fast_reader=False, along with any appropriate arguments to read(). **
** In particular specify the format and any known attributes like the **
** delimiter.                                                         **
************************************************************************

**Comment by eleonorazari** [comment]
Hi Jon, 
I just noticed it's the same as one closed issue. I tried to do what you suggested in the other issue (git pull + python setup.py install), but it does not solve the problem for me.

Eleonora

**Comment by eleonorazari** [comment]
Okay, I was forgetting to activate the ppv environment BEFORE python setup.py install. It's working (and closing the issue).

**Comment by jcbird** [comment]
Wooohoo! I love when things work out even before I can get to them :) Thanks!
