### ISSUE TITLE
No Utah account

### ISSUE THREAD

**Issue by catherinezucker** [jcbird/ppv#16]
Hello! I need to plate vet for the dust team (with  @schlafly) for plates BHM_01 and MWM_02. My Utah account request is submitted but it likely won't be ready in time. Can I get sent the correct files (at catherine.zucker@cfa.harvard.edu). Thanks!

**Comment by jcbird** [comment]
Thanks for requesting the account. I will send a zip file to you asap, but it may not be until this evening.

In the meantime, request access to the SDSS github organization as well at https://wiki.sdss.org/display/DATA/SDSS+GitHub+Organization

Welcome!

**Comment by catherinezucker** [comment]
Thank you! I'm already a member of the SDSS GitHub organization, so I'm all set there.

**Comment by jcbird** [comment]
Email sent a bit ago. Let me know if that takes care of the issue. Thanks!
