### ISSUE TITLE
Can't get targets available on a plate in PPV

### ISSUE THREAD

**Issue by deleenm** [jcbird/ppv#24]
I did a pull on PPV this morning, and now I have a problem finding available targets on a plate. Note the five_plates version of this function works fine.
```python
planet_targetDB = Table.read('targets/mwm_planet_0.1.0_targetdb.fits.gz')
planet_targets = Targets(planet_targetDB)
plate = Plate(15351)
planet_targets.available_in(plate)
```
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-42-75e311629227> in <module>
      1 plate = Plate(15351)
----> 2 planet_targets.available_in(plate)

~/Dropbox/Research/notebooks/SDSS/SDSS-V_Plate_Check/ppv_git/src/ppv/targets.py in available_in(self, pl_field_plrun)
    143             isinstance(pl_field_plrun, fiveplates.Platerun)):
    144             return self._available_in_platerun(pl_field_plrun)
--> 145         return self._available_in_field(pl_field_plrun)  #  SAME logice for plate/field
    146 
    147     def _within(self, catalogIDs):

~/Dropbox/Research/notebooks/SDSS/SDSS-V_Plate_Check/ppv_git/src/ppv/targets.py in _available_in_field(self, FieldorPlate)
    115             print(f'{FieldorPlate} appears to be a platerun. Use available_in_platerun method instead.')
    116             return
--> 117         lookup_key =(FieldorPlate.name, FieldorPlate.platerun)
    118         indx = self._available_indx.get(lookup_key,
    119                                         self._radial_search(FieldorPlate.center,

~/Dropbox/Research/notebooks/SDSS/SDSS-V_Plate_Check/ppv_git/src/ppv/plate.py in __getattr__(self, attr)
    102         Gets column for plate data table.
    103         """
--> 104         return self.targets[attr]
    105 
    106     def property(self, keyword):

~/anaconda3/envs/ppv/lib/python3.8/site-packages/astropy/table/table.py in __getitem__(self, item)
   1600     def __getitem__(self, item):
   1601         if isinstance(item, str):
-> 1602             return self.columns[item]
   1603         elif isinstance(item, (int, np.integer)):
   1604             return self.Row(self, item)

~/anaconda3/envs/ppv/lib/python3.8/site-packages/astropy/table/table.py in __getitem__(self, item)
    237         """
    238         if isinstance(item, str):
--> 239             return OrderedDict.__getitem__(self, item)
    240         elif isinstance(item, (int, np.integer)):
    241             return self.values()[item]

KeyError: 'platerun'
```

**Comment by jcbird** [comment]
Hi Nathan,

This is likely because you are using `Plates` from `ppv.plate`, correct?

I made a distinction in ppv that when the 'plates' are in five_plates, they are referred to as 'fields' with a design_id following the five_plates nomenclature. 

To look up a particular 'plate' in five_plates, you will want to do the following:

`from ppv import fiveplates`
`prun = fiveplates.Platerun('MWM_08')`  # just for info for the next step
`prun.platedata`  # this gives me the platedata table for MWM_08. In the first row, I see the field you want:
<Table length=20>

fieldname   plateid designid ... Nstd_BOSS              notes               platerun

str13      int64   int64   ...   int64                str32                 str6

------------- ------- -------- ... --------- -------------------------------- --------

RV_172+58_btx       0    15351 ...        50 ;New_RV_Field_Center_Exptime1000   MWM_08`

So, to get your field:

`plate = ppv.fiveplates.Field('RV_172+58_btx', design_id=15351)`
`planet_targets.available_in(plate)`

**Comment by jcbird** [comment]
Also, a nice way to do this on a plate by plate basis:

`available_per_plate = [planet_targets.available_in(field) for field in prun.fields]`

**Comment by deleenm** [comment]
Hi Jon,

That is correct. I am trying to look at the plates from 
2021.03.a.mwm-bhm. I used
from ppv.plate import Plate

I have used this code for quite some time, and it suddenly stopped 
working, which is why I was surprised.

The five_plates version with MWM_08 works fine.

Nathan

Jonathan Bird wrote:
> [CAUTION: EXTERNAL EMAIL]
>
> Hi Nathan,
>
> This is likely because you are using |Plates| from |ppv.plate|, correct?
>
> I made a distinction in ppv that when the 'plates' are in five_plates, 
> they are referred to as 'fields' with a design_id following the 
> five_plates nomenclature.
>
> To look up a particular 'plate' in five_plates, you will want to do 
> the following:
>
> |from ppv import fiveplates|
> |prun = fiveplates.Platerun('MWM_08')| # just for info for the next step
> |prun.platedata| # this gives me the platedata table for MWM_08. In 
> the first row, I see the field you want:
>
> fieldname plateid designid ... Nstd_BOSS notes platerun
>
> str13 int64 int64 ... int64 str32 str6
>
> ------------- ------- -------- ... --------- 
> -------------------------------- --------
>
> RV_172+58_btx 0 15351 ... 50 ;New_RV_Field_Center_Exptime1000 MWM_08`
>
> So, to get your field:
>
> |plate = ppv.fiveplates.Field('RV_172+58_btx', design_id=15351)|
> |planet_targets.available_in(plate)|
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjcbird%2Fppv%2Fissues%2F24%23issuecomment-797745676&data=04%7C01%7Cdeleenm%40nku.edu%7C4110b1d063494548106008d8e5980a8f%7Cac3218551f554d0bb2fa531085ca3022%7C0%7C0%7C637511788466276776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mqouSBu9cX5MtCc%2BdOO79%2Burjt3C0fHvCHnNa9Q0Izw%3D&reserved=0>, 
> or unsubscribe 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEVP47LFBOQDAABWMGUVVK3TDJVUZANCNFSM4ZCWA7EQ&data=04%7C01%7Cdeleenm%40nku.edu%7C4110b1d063494548106008d8e5980a8f%7Cac3218551f554d0bb2fa531085ca3022%7C0%7C0%7C637511788466286770%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=60bybwty5h03K1MOI2YnHlRw5%2BaJIVVvQ7jk5m1y3bc%3D&reserved=0>.
>


-- 
Dr. Nathan De Lee
Associate Professor of Astronomy and Physics
Northern Kentucky University
146 Science Center
1 Nunn Drive
Highland Heights, KY 41099
Tel: 859-572-5492
Fax: 859-572-6092
www.nku.edu/~deleen1
***@***.***

**Comment by jcbird** [comment]
Gah! Sorry, there must have been a commit a while back that inadvertently broke this. Functionality restored with commit 9a737e53b98203cb276bcf7f158e43db1790fc15 .
Just do a fresh pull and it should work. Please let me know and thanks!

**Comment by deleenm** [comment]
That did the job! Thanks!
