### ISSUE TITLE
module 'ppv' has no attribute 'allplate_summary'

### ISSUE THREAD

**Issue by deleenm** [jcbird/ppv#4]
# let's say I am interested in plate 15004. Let's look at the plate summary.
ppv.allplate_summary[ppv.allplate_summary['plateid'] == 15004]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-a51f8b679f7d> in <module>
      1 # let's say I am interested in plate 15004. Let's look at the plate summary.
----> 2 ppv.allplate_summary[ppv.allplate_summary['plateid'] == 15004]

AttributeError: module 'ppv' has no attribute 'allplate_summary'

**Comment by jcbird** [comment]
I'll fix this tonight. I forgot I had to break it to get dynamic updating
of the platefiles to work.

**Comment by jcbird** [comment]
Yep, forgot to update syntax in tutorial. fixed in e1cfa1126946df54b9520117d91b5f4fe7592fd7 . Thanks! I'm going to pre-emptively close this. If there is still a problem, comment here or make a new issue.

THANK YOU!
