### ISSUE TITLE
Platerun name in the tutorial

### ISSUE THREAD

**Issue by BGaensicke** [jcbird/ppv#8]
Walking through https://github.com/jcbird/ppv/blob/master/docs/PPV_tutorial.ipynb, 

> plate_run_2020 = Platerun('2020.10.a.bhm-mwm')

the name convention in the platerun you sent as tar file seems to be 2020.10.a.mwm-bhm

**Comment by jcbird** [comment]
Thanks!

Addressed by fb091206752dbdd45a250b236d4806d1a9ecbd5c
